/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.Atendente;
import Modelos.Paciente;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author joaop
 */
public class PagConfVac extends javax.swing.JPanel {

  TelaPrincipal tp;
  Atendente usuarioLogado = null;
  Paciente pSelecionado = null;
  /**
   * Creates new form PagConfVac
   */
  public PagConfVac(Paciente p, Atendente usuarioLogado, TelaPrincipal tp) {
    this.tp = tp;
    this.usuarioLogado = usuarioLogado;
    this.pSelecionado = p;
    initComponents();
    selecionarTela();
    if(pSelecionado != null) setInfo();
  }
  
  private void setInfo(){
    String saude = pSelecionado.isSaude() ? "Sim" : "Não";
    String dVac = pSelecionado.getDataVac() == null ? "---" : pSelecionado.getDataVac().toString();
    String vacPor = pSelecionado.getNomeVacPor() == null ? "---" : pSelecionado.getNomeVacPor().toString();
    txtCpf.setText(txtCpf.getText() + pSelecionado.getCpf());
    txtNome.setText(txtNome.getText() + pSelecionado.getNome());
    txtIdade.setText(txtIdade.getText() + pSelecionado.getIdade());
    txtSaude.setText(txtSaude.getText() + saude);
    txtDataVac.setText(txtDataVac.getText() + dVac);
    txtVacPor.setText(txtVacPor.getText() + vacPor);
  }
  
  private void selecionarTela(){
    if (pSelecionado == null){
      pnBase.add(pnBuscaPaciente);
    }else{
      pnBase.add(pnInfoPaciente);
    }
    revalidate();
    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnBuscaPaciente = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    campoBuscaCpf = new javax.swing.JFormattedTextField();
    jLabel2 = new javax.swing.JLabel();
    btnBusca = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    pnInfoPaciente = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txtCpf = new javax.swing.JLabel();
    txtNome = new javax.swing.JLabel();
    txtIdade = new javax.swing.JLabel();
    txtSaude = new javax.swing.JLabel();
    txtDataVac = new javax.swing.JLabel();
    btnConfVac = new javax.swing.JButton();
    txtVacPor = new javax.swing.JLabel();
    pnBase = new javax.swing.JPanel();

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Buscar Paciente");

    try {
      campoBuscaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    campoBuscaCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("CPF");

    btnBusca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnBusca.setText("Buscar");
    btnBusca.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscaActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Confirmar Vacinação");

    javax.swing.GroupLayout pnBuscaPacienteLayout = new javax.swing.GroupLayout(pnBuscaPaciente);
    pnBuscaPaciente.setLayout(pnBuscaPacienteLayout);
    pnBuscaPacienteLayout.setHorizontalGroup(
      pnBuscaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscaPacienteLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(pnBuscaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel2)
          .addComponent(campoBuscaCpf)
          .addComponent(btnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        .addGap(230, 230, 230))
      .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
    );
    pnBuscaPacienteLayout.setVerticalGroup(
      pnBuscaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnBuscaPacienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addGap(50, 50, 50)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoBuscaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(294, Short.MAX_VALUE))
    );

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Confirmar Vacinação");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Informações do Paciente");

    txtCpf.setText("CPF: ");

    txtNome.setText("Nome: ");

    txtIdade.setText("Idade: ");

    txtSaude.setText("Profissional de Saúde: ");

    txtDataVac.setText("Data de Vacinação: ");

    btnConfVac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnConfVac.setText("Confirmar Vacina");
    btnConfVac.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConfVacActionPerformed(evt);
      }
    });

    txtVacPor.setText("Vacinado por: ");

    javax.swing.GroupLayout pnInfoPacienteLayout = new javax.swing.GroupLayout(pnInfoPaciente);
    pnInfoPaciente.setLayout(pnInfoPacienteLayout);
    pnInfoPacienteLayout.setHorizontalGroup(
      pnInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
      .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pnInfoPacienteLayout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addGroup(pnInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtVacPor)
          .addComponent(txtDataVac)
          .addComponent(txtSaude)
          .addComponent(txtIdade)
          .addComponent(txtNome)
          .addComponent(txtCpf))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInfoPacienteLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnConfVac)
        .addGap(227, 227, 227))
    );
    pnInfoPacienteLayout.setVerticalGroup(
      pnInfoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnInfoPacienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addGap(35, 35, 35)
        .addComponent(txtCpf)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtNome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtIdade)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtSaude)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtDataVac)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtVacPor)
        .addGap(18, 18, 18)
        .addComponent(btnConfVac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(226, Short.MAX_VALUE))
    );

    setPreferredSize(new java.awt.Dimension(600, 560));
    setLayout(new java.awt.BorderLayout());

    pnBase.setLayout(new java.awt.BorderLayout());
    add(pnBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
    new Thread(() -> {
      tp.carregando();
      campoBuscaCpf.setEnabled(false);
      btnBusca.setEnabled(false);
      this.pSelecionado = usuarioLogado.buscarParaVac(campoBuscaCpf.getText());
      if (this.pSelecionado != null) {
        pnBase.remove(0);
        pnBase.add(pnInfoPaciente);
        if (pSelecionado.getDataVac() != null) {
          btnConfVac.setEnabled(false);
        }
        revalidate();
        repaint();
        setInfo();
      }
      tp.carregando();
      campoBuscaCpf.setEnabled(true);
      btnBusca.setEnabled(true);
    }).start();
  }//GEN-LAST:event_btnBuscaActionPerformed

  private void btnConfVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfVacActionPerformed
    new Thread(() -> {
      btnConfVac.setEnabled(false);
      tp.carregando();
      int cod = usuarioLogado.confVac(pSelecionado, usuarioLogado);
      if(cod > 0){
        txtDataVac.setText("Data de Vacinação: " + pSelecionado.getDataVac().format(DateTimeFormatter.ofPattern("d/M/y")));
        txtVacPor.setText("Vacinado por: " + usuarioLogado.getNome());
        tp.fila = null;
        tp.s = null;
      } else {
        btnConfVac.setEnabled(true);
      }
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnConfVacActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBusca;
  private javax.swing.JButton btnConfVac;
  private javax.swing.JFormattedTextField campoBuscaCpf;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel pnBase;
  private javax.swing.JPanel pnBuscaPaciente;
  private javax.swing.JPanel pnInfoPaciente;
  private javax.swing.JLabel txtCpf;
  private javax.swing.JLabel txtDataVac;
  private javax.swing.JLabel txtIdade;
  private javax.swing.JLabel txtNome;
  private javax.swing.JLabel txtSaude;
  private javax.swing.JLabel txtVacPor;
  // End of variables declaration//GEN-END:variables
}
