/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.AnimaNumeros;
import Modelos.Relatorio;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author joaop
 */
public class PagGerarRelat extends javax.swing.JPanel implements AnimaNumeros{

  private TelaPrincipal tp;
  private Date ultDi = new Date();
  private Date ultDf = new Date();
  
  /**
   * Creates new form PagGerarRelat
   */
  public PagGerarRelat(TelaPrincipal tp) {
    this.tp = tp;
    initComponents();
    depoisInit();
  }
  
  private void depoisInit(){
    pnPrincipal.setVisible(false);
    campoDataInicial.getJCalendar().setPreferredSize(new Dimension(300,200));
    campoDataFinal.getJCalendar().setPreferredSize(new Dimension(300,200));
    campoDataInicial.setIcon(new ImageIcon(getClass().getResource("/icons8_calendar_26px.png")));
    campoDataFinal.setIcon(new ImageIcon(getClass().getResource("/icons8_calendar_26px.png")));
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnBase = new javax.swing.JPanel();
    pnTopo = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    campoDataInicial = new com.toedter.calendar.JDateChooser();
    jLabel3 = new javax.swing.JLabel();
    campoDataFinal = new com.toedter.calendar.JDateChooser();
    btnGerarRelatorio = new javax.swing.JButton();
    pnPrincipal = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    txtM1 = new javax.swing.JLabel();
    txtValM1 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    txtM2 = new javax.swing.JLabel();
    txtValM2 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    txtM3 = new javax.swing.JLabel();
    txtValM3 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    txtM4 = new javax.swing.JLabel();
    txtValM4 = new javax.swing.JLabel();

    setPreferredSize(new java.awt.Dimension(600, 560));
    setLayout(new java.awt.BorderLayout());

    pnBase.setLayout(new java.awt.BorderLayout());

    pnTopo.setPreferredSize(new java.awt.Dimension(600, 188));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Gerar Relatório");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("Data Inicial");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Data Final");

    btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGerarRelatorio.setText("Gerar Relatório");
    btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGerarRelatorioActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
    pnTopo.setLayout(pnTopoLayout);
    pnTopoLayout.setHorizontalGroup(
      pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pnTopoLayout.createSequentialGroup()
        .addGap(100, 100, 100)
        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(campoDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(100, 100, 100))
      .addGroup(pnTopoLayout.createSequentialGroup()
        .addGap(233, 233, 233)
        .addComponent(btnGerarRelatorio)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnTopoLayout.setVerticalGroup(
      pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnTopoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(pnTopoLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(pnTopoLayout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnBase.add(pnTopo, java.awt.BorderLayout.PAGE_START);

    pnPrincipal.setLayout(new java.awt.BorderLayout());

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Vacinações por dia");
    jLabel5.setPreferredSize(new java.awt.Dimension(216, 50));
    pnPrincipal.add(jLabel5, java.awt.BorderLayout.PAGE_START);

    jPanel1.setLayout(new java.awt.GridLayout(2, 2));

    jPanel2.setLayout(new java.awt.BorderLayout());

    txtM1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    txtM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtM1.setText("Pessoas acima de 89 anos");
    txtM1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    txtM1.setPreferredSize(new java.awt.Dimension(249, 60));
    jPanel2.add(txtM1, java.awt.BorderLayout.PAGE_END);

    txtValM1.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValM1.setText("0");
    txtValM1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel2.add(txtValM1, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel2);

    jPanel3.setLayout(new java.awt.BorderLayout());

    txtM2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    txtM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtM2.setText("Pessoas de 70 a 89 anos");
    txtM2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    txtM2.setPreferredSize(new java.awt.Dimension(229, 60));
    jPanel3.add(txtM2, java.awt.BorderLayout.PAGE_END);

    txtValM2.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValM2.setText("0");
    txtValM2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel3.add(txtValM2, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel3);

    jPanel4.setLayout(new java.awt.BorderLayout());

    txtM3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    txtM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtM3.setText("Pessoas de 50 a 69 anos");
    txtM3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    txtM3.setPreferredSize(new java.awt.Dimension(229, 60));
    jPanel4.add(txtM3, java.awt.BorderLayout.PAGE_END);

    txtValM3.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValM3.setText("0");
    txtValM3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel4.add(txtValM3, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel4);

    jPanel5.setLayout(new java.awt.BorderLayout());

    txtM4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    txtM4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtM4.setText("Pessoas abaixo de 50 anos");
    txtM4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    txtM4.setPreferredSize(new java.awt.Dimension(251, 60));
    jPanel5.add(txtM4, java.awt.BorderLayout.PAGE_END);

    txtValM4.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValM4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValM4.setText("0");
    txtValM4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    jPanel5.add(txtValM4, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel5);

    pnPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

    pnBase.add(pnPrincipal, java.awt.BorderLayout.CENTER);

    add(pnBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
    new Thread(() -> {
      tp.carregando();
      btnGerarRelatorio.setEnabled(false);
      campoDataFinal.setEnabled(false);
      campoDataInicial.setEnabled(false);
      Date di = campoDataInicial.getDate();
      Date df = campoDataFinal.getDate();
      
      if(di == null || df == null){
        JOptionPane.showMessageDialog(null, "Preencha as datas por favor!", "Aviso", JOptionPane.WARNING_MESSAGE);
      } else if(di.getTime() == ultDi.getTime() && df.getTime() == ultDf.getTime()){
        
      }else{
        ultDf = df;
        ultDi = di;
        
        if(di.after(df)){
          JOptionPane.showMessageDialog(null, "A data final não pode ser anterior à data inicial!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else{
          
        Relatorio re = new Relatorio(di, df);

        animarNumeros(txtValM1, re.getM1(), 0.75);
        animarNumeros(txtValM2, re.getM2(), 0.75);
        animarNumeros(txtValM3, re.getM3(), 0.75);
        animarNumeros(txtValM4, re.getM4(), 0.75);

        pnPrincipal.setVisible(true);
        }
        
        
      }
      
      btnGerarRelatorio.setEnabled(true);
      campoDataFinal.setEnabled(true);
      campoDataInicial.setEnabled(true);
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnGerarRelatorioActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnGerarRelatorio;
  private com.toedter.calendar.JDateChooser campoDataFinal;
  private com.toedter.calendar.JDateChooser campoDataInicial;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel pnBase;
  private javax.swing.JPanel pnPrincipal;
  private javax.swing.JPanel pnTopo;
  private javax.swing.JLabel txtM1;
  private javax.swing.JLabel txtM2;
  private javax.swing.JLabel txtM3;
  private javax.swing.JLabel txtM4;
  private javax.swing.JLabel txtValM1;
  private javax.swing.JLabel txtValM2;
  private javax.swing.JLabel txtValM3;
  private javax.swing.JLabel txtValM4;
  // End of variables declaration//GEN-END:variables
}
