/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.Administrador;
import Modelos.Atendente;
import java.awt.Cursor;
import java.util.regex.Pattern;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author joaop
 */
public class PagGerUsuarios extends javax.swing.JPanel {

  private Atendente usuarioLogado;
  private TelaPrincipal tp;
  
  /**
   * Creates new form PagGerUsuarios
   */
  public PagGerUsuarios(Atendente u, TelaPrincipal tp) {
    this.tp = tp;
    this.usuarioLogado = u;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jtpBase = new javax.swing.JTabbedPane();
    addUsuario = new javax.swing.JPanel();
    campoCpf = new javax.swing.JFormattedTextField();
    jLabel1 = new javax.swing.JLabel();
    campoNome = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    campoSenha = new javax.swing.JPasswordField();
    jLabel3 = new javax.swing.JLabel();
    campoRepSenha = new javax.swing.JPasswordField();
    jLabel4 = new javax.swing.JLabel();
    cbAdmin = new javax.swing.JCheckBox();
    btnAddUsuario = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();
    altUsuario = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    campoSenhaAlt = new javax.swing.JPasswordField();
    jLabel6 = new javax.swing.JLabel();
    campoRepSenhaAlt = new javax.swing.JPasswordField();
    jLabel7 = new javax.swing.JLabel();
    cbAdminAlt = new javax.swing.JCheckBox();
    campoCpfAlt = new javax.swing.JFormattedTextField();
    jLabel8 = new javax.swing.JLabel();
    campoNomeAlt = new javax.swing.JTextField();
    btnBuscarCpf = new javax.swing.JButton();
    btnExcluirUsuario = new javax.swing.JButton();
    btnAtualizarUsuario = new javax.swing.JButton();
    btnLimparAlt = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(600, 560));
    setLayout(new java.awt.BorderLayout());

    jtpBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    try {
      campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    campoCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        campoCpfActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("CPF");

    campoNome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        campoNomeActionPerformed(evt);
      }
    });
    campoNome.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoNomeKeyTyped(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("Nome");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Senha");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setText("Repita Senha");

    cbAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    cbAdmin.setText("Administrador");
    cbAdmin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbAdminActionPerformed(evt);
      }
    });

    btnAddUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnAddUsuario.setText("Adicionar Atendente");
    btnAddUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddUsuarioActionPerformed(evt);
      }
    });

    btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLimpar.setText("Limpar Campos");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout addUsuarioLayout = new javax.swing.GroupLayout(addUsuario);
    addUsuario.setLayout(addUsuarioLayout);
    addUsuarioLayout.setHorizontalGroup(
      addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addUsuarioLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addUsuarioLayout.createSequentialGroup()
            .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1))
            .addGap(18, 18, 18)
            .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 132, Short.MAX_VALUE))
          .addGroup(addUsuarioLayout.createSequentialGroup()
            .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(addUsuarioLayout.createSequentialGroup()
                .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel4)
                  .addComponent(campoRepSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(addUsuarioLayout.createSequentialGroup()
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(btnAddUsuario))
              .addComponent(cbAdmin))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    addUsuarioLayout.setVerticalGroup(
      addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addUsuarioLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(addUsuarioLayout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoRepSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(addUsuarioLayout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(30, 30, 30)
        .addComponent(cbAdmin)
        .addGap(30, 30, 30)
        .addGroup(addUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(205, Short.MAX_VALUE))
    );

    jtpBase.addTab("Adicionar Usuário", new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_male_25px_1.png")), addUsuario); // NOI18N

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel5.setText("Nome");

    campoSenhaAlt.setEnabled(false);

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel6.setText("Nova Senha");

    campoRepSenhaAlt.setEnabled(false);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel7.setText("Repita Senha");

    cbAdminAlt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    cbAdminAlt.setText("Administrador");
    cbAdminAlt.setEnabled(false);
    cbAdminAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbAdminAltActionPerformed(evt);
      }
    });

    try {
      campoCpfAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel8.setText("CPF");

    campoNomeAlt.setEnabled(false);
    campoNomeAlt.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoNomeAltKeyTyped(evt);
      }
    });

    btnBuscarCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnBuscarCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_22px.png"))); // NOI18N
    btnBuscarCpf.setFocusPainted(false);
    btnBuscarCpf.setIconTextGap(10);
    btnBuscarCpf.setMargin(new java.awt.Insets(2, 10, 2, 10));
    btnBuscarCpf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarCpfActionPerformed(evt);
      }
    });

    btnExcluirUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnExcluirUsuario.setText("Excluir Usuário");
    btnExcluirUsuario.setEnabled(false);
    btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirUsuarioActionPerformed(evt);
      }
    });

    btnAtualizarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnAtualizarUsuario.setText("Atualizar Usuário");
    btnAtualizarUsuario.setEnabled(false);
    btnAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAtualizarUsuarioActionPerformed(evt);
      }
    });

    btnLimparAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_broom_32px.png"))); // NOI18N
    btnLimparAlt.setFocusPainted(false);
    btnLimparAlt.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnLimparAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparAltActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout altUsuarioLayout = new javax.swing.GroupLayout(altUsuario);
    altUsuario.setLayout(altUsuarioLayout);
    altUsuarioLayout.setHorizontalGroup(
      altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(altUsuarioLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(altUsuarioLayout.createSequentialGroup()
            .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(altUsuarioLayout.createSequentialGroup()
                .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel6)
                  .addComponent(campoSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel7)
                  .addComponent(campoRepSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(cbAdminAlt))
            .addContainerGap(312, Short.MAX_VALUE))
          .addGroup(altUsuarioLayout.createSequentialGroup()
            .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(altUsuarioLayout.createSequentialGroup()
                .addComponent(btnExcluirUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarUsuario))
              .addComponent(jLabel5)
              .addComponent(campoNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(altUsuarioLayout.createSequentialGroup()
                .addComponent(campoCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparAlt))
              .addComponent(jLabel8))
            .addGap(0, 0, Short.MAX_VALUE))))
    );
    altUsuarioLayout.setVerticalGroup(
      altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(altUsuarioLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(campoCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBuscarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnLimparAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(altUsuarioLayout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoRepSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(altUsuarioLayout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(30, 30, 30)
        .addComponent(cbAdminAlt)
        .addGap(30, 30, 30)
        .addGroup(altUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnAtualizarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(109, Short.MAX_VALUE))
    );

    jtpBase.addTab("Alterar Usuário", new javax.swing.ImageIcon(getClass().getResource("/icons8_registration_25px_1.png")), altUsuario); // NOI18N

    add(jtpBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void setTextoBotaoAdd(){
    if(cbAdmin.isSelected()){
      btnAddUsuario.setText("Adicionar Administrador");
    }else{
      btnAddUsuario.setText("Adicionar Atendente");
    }
  }
  
  private void es1Alt(){
    campoCpfAlt.setEnabled(true);
    btnBuscarCpf.setEnabled(true);
    btnLimparAlt.setEnabled(true);
    campoNomeAlt.setEnabled(false);
    campoSenhaAlt.setEnabled(false);
    campoRepSenhaAlt.setEnabled(false);
    cbAdminAlt.setEnabled(false);
    btnExcluirUsuario.setEnabled(false);
    btnAtualizarUsuario.setEnabled(false);
  }
  
  private void es2Alt(){
    campoCpfAlt.setEnabled(false);
    btnBuscarCpf.setEnabled(false);
    btnLimparAlt.setEnabled(true);
    campoNomeAlt.setEnabled(true);
    campoSenhaAlt.setEnabled(true);
    campoRepSenhaAlt.setEnabled(true);
    cbAdminAlt.setEnabled(true);
    btnExcluirUsuario.setEnabled(true);
    btnAtualizarUsuario.setEnabled(true);
  }
  
  private void esTudoOff(){
    campoCpfAlt.setEnabled(false);
    btnBuscarCpf.setEnabled(false);
    btnLimparAlt.setEnabled(false);
    campoNomeAlt.setEnabled(false);
    campoSenhaAlt.setEnabled(false);
    campoRepSenhaAlt.setEnabled(false);
    cbAdminAlt.setEnabled(false);
    btnExcluirUsuario.setEnabled(false);
    btnAtualizarUsuario.setEnabled(false);
  }
  
  private void limparCamposCad(){
    campoCpf.setValue(null);
    campoNome.setText("");
    campoSenha.setText("");
    campoRepSenha.setText("");
    cbAdmin.setSelected(false);
    setTextoBotaoAdd();
  }
  
  private void limparCamposAlt(){
    es1Alt();
    campoCpfAlt.setValue(null);
    campoNomeAlt.setText("");
    campoSenhaAlt.setText("");
    campoRepSenhaAlt.setText("");
    cbAdminAlt.setSelected(false);
    setTextoBotaoAdd();
  }
  
  private void carregandoCad() {
    if (getCursor().getType() == Cursor.DEFAULT_CURSOR) {
      tp.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    } else {
      tp.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    tp.toggleBotoes();

    jtpBase.setEnabled(!jtpBase.isEnabled());
    campoCpf.setEnabled(!campoCpf.isEnabled());
    campoNome.setEnabled(!campoNome.isEnabled());
    campoSenha.setEnabled(!campoSenha.isEnabled());
    campoRepSenha.setEnabled(!campoRepSenha.isEnabled());
    cbAdmin.setEnabled(!cbAdmin.isEnabled());
    btnAddUsuario.setEnabled(!btnAddUsuario.isEnabled());
    btnLimpar.setEnabled(!btnLimpar.isEnabled());
  }
  
  private void carregandoAlt() {
    if (getCursor().getType() == Cursor.DEFAULT_CURSOR) {
      tp.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    } else {
      tp.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
    
    tp.toggleBotoes();

    jtpBase.setEnabled(!jtpBase.isEnabled());
  }  
  
  private void cbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdminActionPerformed
    setTextoBotaoAdd();
  }//GEN-LAST:event_cbAdminActionPerformed

  private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    limparCamposCad();
  }//GEN-LAST:event_btnLimparActionPerformed

  private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_campoCpfActionPerformed

  private void btnAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsuarioActionPerformed
    new Thread(() -> {
      carregandoCad();
      if (usuarioLogado.cadUsuario(campoCpf.getText(), campoNome.getText(), new String(campoSenha.getPassword()), new String(campoRepSenha.getPassword()), cbAdmin.isSelected()) == 1) {
        System.out.println("sucesso");
        limparCamposCad();
      } else {
        System.out.println("erro");
      }
      carregandoCad();
    }).start();
  }//GEN-LAST:event_btnAddUsuarioActionPerformed

  private void cbAdminAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAdminAltActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cbAdminAltActionPerformed

  private void btnBuscarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCpfActionPerformed
    new Thread(() -> {
      carregandoAlt();
      esTudoOff();
      Atendente u = usuarioLogado.buscarUsuario(campoCpfAlt.getText());
      if (u == null) { //busca falhou
        carregandoAlt();
        limparCamposAlt();
        return;
      }
      //busca sucesso
      es2Alt();
      campoNomeAlt.setText(u.getNome());
      campoSenhaAlt.setText(u.getSenha());
      campoRepSenhaAlt.setText(u.getSenha());
      if (u.getClass().equals(Administrador.class)) {
        cbAdminAlt.setSelected(true);
      } else {
        cbAdminAlt.setSelected(false);
      }
      carregandoAlt();
    }).start();
  }//GEN-LAST:event_btnBuscarCpfActionPerformed

  private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
    new Thread(() -> {
      carregandoAlt();
      esTudoOff();
      if (usuarioLogado.removerUsuario(campoCpfAlt.getText())) {//remover sucesso
        System.out.println("sucesso");
        limparCamposAlt();
      } else { //remover falhou
        System.out.println("erro");
        es1Alt();
      }
      carregandoAlt();
    }).start();
  }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

  private void btnAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarUsuarioActionPerformed
    new Thread(() -> {
      carregandoAlt();
      esTudoOff();
      if (usuarioLogado.atualizarUsuario(campoCpfAlt.getText(),
              campoNomeAlt.getText(), new String(campoSenhaAlt.getPassword()),
              new String(campoRepSenhaAlt.getPassword()), cbAdminAlt.isSelected())) {
        limparCamposAlt();
      }else{
        es1Alt();
      }
      carregandoAlt();
    }).start();
  }//GEN-LAST:event_btnAtualizarUsuarioActionPerformed

  private void btnLimparAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAltActionPerformed
    limparCamposAlt();
  }//GEN-LAST:event_btnLimparAltActionPerformed

  private void campoNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeKeyTyped
    if (Pattern.matches("[0-9!@#$%^&*()]", String.valueOf(evt.getKeyChar()))) evt.consume();
  }//GEN-LAST:event_campoNomeKeyTyped

  private void campoNomeAltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeAltKeyTyped
    if (Pattern.matches("[0-9!@#$%^&*()]", String.valueOf(evt.getKeyChar()))) evt.consume();
  }//GEN-LAST:event_campoNomeAltKeyTyped

  private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_campoNomeActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel addUsuario;
  private javax.swing.JPanel altUsuario;
  private javax.swing.JButton btnAddUsuario;
  private javax.swing.JButton btnAtualizarUsuario;
  private javax.swing.JButton btnBuscarCpf;
  private javax.swing.JButton btnExcluirUsuario;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnLimparAlt;
  private javax.swing.JFormattedTextField campoCpf;
  private javax.swing.JFormattedTextField campoCpfAlt;
  private javax.swing.JTextField campoNome;
  private javax.swing.JTextField campoNomeAlt;
  private javax.swing.JPasswordField campoRepSenha;
  private javax.swing.JPasswordField campoRepSenhaAlt;
  private javax.swing.JPasswordField campoSenha;
  private javax.swing.JPasswordField campoSenhaAlt;
  private javax.swing.JCheckBox cbAdmin;
  private javax.swing.JCheckBox cbAdminAlt;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JTabbedPane jtpBase;
  // End of variables declaration//GEN-END:variables
}
