/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.Atendente;
import Modelos.Endereco;
import Modelos.Paciente;
import java.awt.Cursor;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JComponent;

/**
 *
 * @author joaop
 */
public class PagGerPacientes extends javax.swing.JPanel {

  private Atendente usuarioLogado;
  private Paciente pacienteBuscado = null;
  private Endereco enderecoCad;
  private TelaPrincipal tp;
  private boolean sabeCep = true;
  
  /**
   * Creates new form PagGerPacientes
   */
  public PagGerPacientes(Atendente u, TelaPrincipal tp) {
    this.usuarioLogado = u;
    this.tp = tp;
    initComponents();
    campoDataNasc.getJCalendar().setPreferredSize(new Dimension(300,200));
    campoDataNascAlt.getJCalendar().setPreferredSize(new Dimension(300,200));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jtbBase = new javax.swing.JTabbedPane();
    addPaciente = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    campoCpfCad = new javax.swing.JFormattedTextField();
    jLabel2 = new javax.swing.JLabel();
    campoNomeCad = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    campoDataNasc = new com.toedter.calendar.JDateChooser();
    campoSaudeCad = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    campoCepCad = new javax.swing.JFormattedTextField();
    btnBuscarCep = new javax.swing.JButton();
    campoRuaCad = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    campoNumCad = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    btnNaoSeiCep = new javax.swing.JButton();
    jLabel11 = new javax.swing.JLabel();
    campoComplemento = new javax.swing.JTextField();
    btnCadPaciente = new javax.swing.JButton();
    btnLimpar = new javax.swing.JButton();
    campoEstado = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    campoCidade = new javax.swing.JTextField();
    campoBairro = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    altPaciente = new javax.swing.JPanel();
    btnAtuPacienteAlt = new javax.swing.JButton();
    btnExcluirAlt = new javax.swing.JButton();
    campoEstadoAlt = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    campoCidadeAlt = new javax.swing.JTextField();
    campoBairroAlt = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    campoSaudeAlt = new javax.swing.JComboBox<>();
    jLabel10 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    campoCepAlt = new javax.swing.JFormattedTextField();
    btnBuscarCpfAlt = new javax.swing.JButton();
    campoRuaAlt = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    campoNumAlt = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    campoCpfAlt = new javax.swing.JFormattedTextField();
    jLabel20 = new javax.swing.JLabel();
    campoNomeAlt = new javax.swing.JTextField();
    jLabel21 = new javax.swing.JLabel();
    campoDataNascAlt = new com.toedter.calendar.JDateChooser();
    jLabel22 = new javax.swing.JLabel();
    campoComplementoAlt = new javax.swing.JTextField();
    btnLimparAlt = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    jtbBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("CPF*");

    try {
      campoCpfCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("Nome Completo*");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Data de Nascimento*");

    campoDataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_calendar_26px.png")));
    campoDataNasc.setMinSelectableDate(new java.util.Date(-62135755138000L));

    campoSaudeCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setText("Trabalha na área da Saúde");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel5.setText("CEP");

    try {
      campoCepCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    btnBuscarCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_22px.png"))); // NOI18N
    btnBuscarCep.setMargin(new java.awt.Insets(2, 10, 2, 10));
    btnBuscarCep.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarCepActionPerformed(evt);
      }
    });

    campoRuaCad.setEnabled(false);

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel6.setText("Rua*");

    campoNumCad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    campoNumCad.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoNumCadKeyTyped(evt);
      }
    });

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel7.setText("Número*");

    btnNaoSeiCep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnNaoSeiCep.setText("Não sei meu CEP");
    btnNaoSeiCep.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNaoSeiCepActionPerformed(evt);
      }
    });

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel11.setText("Complemento");

    btnCadPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnCadPaciente.setText("Cadastrar Paciente");
    btnCadPaciente.setEnabled(false);
    btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadPacienteActionPerformed(evt);
      }
    });

    btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLimpar.setText("Limpar");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparActionPerformed(evt);
      }
    });

    campoEstado.setEnabled(false);
    campoEstado.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        campoEstadoKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoEstadoKeyTyped(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel8.setText("Estado*");

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel12.setText("Cidade*");

    campoCidade.setEnabled(false);

    campoBairro.setEnabled(false);

    jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel13.setText("Bairro");

    javax.swing.GroupLayout addPacienteLayout = new javax.swing.GroupLayout(addPaciente);
    addPaciente.setLayout(addPacienteLayout);
    addPacienteLayout.setHorizontalGroup(
      addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addPacienteLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addComponent(btnCadPaciente)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))
            .addGap(18, 18, 18)
            .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel4)
              .addComponent(campoSaudeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPacienteLayout.createSequentialGroup()
              .addComponent(campoCepCad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(btnBuscarCep)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(btnNaoSeiCep))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPacienteLayout.createSequentialGroup()
              .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(campoCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGap(18, 18, 18)
              .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(campoNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(campoRuaCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11)
                .addComponent(campoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jLabel6))
            .addGap(18, 18, 18)
            .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel12)
              .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(campoCidade, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(campoBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
            .addGap(18, 18, 18)
            .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel8)
              .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7)
              .addComponent(campoNumCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(30, Short.MAX_VALUE))
    );
    addPacienteLayout.setVerticalGroup(
      addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addPacienteLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoCpfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(campoSaudeCad, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
          .addComponent(campoDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btnNaoSeiCep, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
          .addComponent(btnBuscarCep, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
          .addComponent(campoCepCad))
        .addGap(18, 18, 18)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(addPacienteLayout.createSequentialGroup()
              .addComponent(jLabel6)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoRuaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jLabel11)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(addPacienteLayout.createSequentialGroup()
              .addComponent(jLabel13)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel12)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(addPacienteLayout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoNumCad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(addPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    jtbBase.addTab("Adicionar Paciente", new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_male_25px_1.png")), addPaciente); // NOI18N

    btnAtuPacienteAlt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnAtuPacienteAlt.setText("Atualizar Paciente");
    btnAtuPacienteAlt.setEnabled(false);
    btnAtuPacienteAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAtuPacienteAltActionPerformed(evt);
      }
    });

    btnExcluirAlt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnExcluirAlt.setText("Excluir");
    btnExcluirAlt.setEnabled(false);
    btnExcluirAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirAltActionPerformed(evt);
      }
    });

    campoEstadoAlt.setEnabled(false);
    campoEstadoAlt.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        campoEstadoAltKeyReleased(evt);
      }
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoEstadoAltKeyTyped(evt);
      }
    });

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel9.setText("Estado*");

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel14.setText("Cidade*");

    campoCidadeAlt.setEnabled(false);

    campoBairroAlt.setEnabled(false);

    jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel15.setText("Bairro");

    campoSaudeAlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
    campoSaudeAlt.setEnabled(false);

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel10.setText("Trabalha na área da Saúde");

    jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel16.setText("CEP");

    try {
      campoCepAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    campoCepAlt.setEnabled(false);

    btnBuscarCpfAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_22px.png"))); // NOI18N
    btnBuscarCpfAlt.setMargin(new java.awt.Insets(2, 10, 2, 10));
    btnBuscarCpfAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarCpfAltActionPerformed(evt);
      }
    });

    campoRuaAlt.setEnabled(false);

    jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel17.setText("Rua*");

    campoNumAlt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    campoNumAlt.setEnabled(false);
    campoNumAlt.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        campoNumAltKeyTyped(evt);
      }
    });

    jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel18.setText("Número*");

    jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel19.setText("CPF");

    try {
      campoCpfAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }

    jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel20.setText("Nome Completo*");

    campoNomeAlt.setEnabled(false);

    jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel21.setText("Data de Nascimento*");

    campoDataNascAlt.setEnabled(false);
    campoDataNascAlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_calendar_26px.png")));
    campoDataNascAlt.setMinSelectableDate(new java.util.Date(-62135755138000L));

    jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel22.setText("Complemento");

    campoComplementoAlt.setEnabled(false);

    btnLimparAlt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLimparAlt.setText("Limpar");
    btnLimparAlt.setEnabled(false);
    btnLimparAlt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimparAltActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout altPacienteLayout = new javax.swing.GroupLayout(altPaciente);
    altPaciente.setLayout(altPacienteLayout);
    altPacienteLayout.setHorizontalGroup(
      altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(altPacienteLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(altPacienteLayout.createSequentialGroup()
            .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(campoCepAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel16)
              .addGroup(altPacienteLayout.createSequentialGroup()
                .addComponent(campoCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCpfAlt)
                .addGap(18, 18, 18)
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel20)
                  .addComponent(campoNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 30, Short.MAX_VALUE))
          .addGroup(altPacienteLayout.createSequentialGroup()
            .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel19)
              .addGroup(altPacienteLayout.createSequentialGroup()
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(campoDataNascAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10)
                  .addComponent(campoSaudeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(altPacienteLayout.createSequentialGroup()
                .addComponent(btnLimparAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(btnExcluirAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtuPacienteAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(altPacienteLayout.createSequentialGroup()
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRuaAlt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(campoComplementoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel14)
                  .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoCidadeAlt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBairroAlt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel9)
                  .addComponent(campoEstadoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel18)
                  .addComponent(campoNumAlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(30, Short.MAX_VALUE))))
    );
    altPacienteLayout.setVerticalGroup(
      altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(altPacienteLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(altPacienteLayout.createSequentialGroup()
            .addComponent(jLabel20)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(altPacienteLayout.createSequentialGroup()
            .addComponent(jLabel19)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnBuscarCpfAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel21)
          .addComponent(jLabel10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(campoSaudeAlt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
          .addComponent(campoDataNascAlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(jLabel16)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(campoCepAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(altPacienteLayout.createSequentialGroup()
              .addComponent(jLabel17)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoRuaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(18, 18, 18)
              .addComponent(jLabel22)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoComplementoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(altPacienteLayout.createSequentialGroup()
              .addComponent(jLabel15)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoBairroAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel14)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(campoCidadeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(altPacienteLayout.createSequentialGroup()
            .addComponent(jLabel18)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoNumAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(campoEstadoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(altPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(btnAtuPacienteAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnExcluirAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnLimparAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    jtbBase.addTab("Alterar Paciente", new javax.swing.ImageIcon(getClass().getResource("/icons8_registration_25px_1.png")), altPaciente); // NOI18N

    add(jtbBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  
  private void setEstadoCad(boolean b, JComponent[] lista) {
//    setEstado(false, new JComponent[]{campoCepCad, btnCadPaciente});
    List<JComponent> a = Arrays.asList(lista);
    JComponent[] x = {jtbBase, campoCpfCad, campoNomeCad, campoDataNasc, campoSaudeCad, campoCepCad,
      btnBuscarCep, btnNaoSeiCep, campoRuaCad, campoBairro, campoNumCad, campoComplemento, campoCidade, campoEstado, btnCadPaciente, btnLimpar};
    for (JComponent c : x) {
      if (a.contains(c)) {
        c.setEnabled(b);
      } else {
        c.setEnabled(!b);
      }
    }
  }
  
  private void setEstadoAlt(boolean b, JComponent[] lista) {
//    setEstado(false, new JComponent[]{campoCepCad, btnCadPaciente});
    List<JComponent> a = Arrays.asList(lista);
    JComponent[] x = {jtbBase, campoCpfAlt, campoNomeAlt, campoDataNascAlt, campoSaudeAlt, campoCepAlt,
      btnExcluirAlt, btnBuscarCpfAlt, btnAtuPacienteAlt, btnLimparAlt, campoRuaAlt, campoBairroAlt, campoNumAlt, campoComplementoAlt, campoCidadeAlt, campoEstadoAlt};
    for (JComponent c : x) {
      if (a.contains(c)) {
        c.setEnabled(b);
      } else {
        c.setEnabled(!b);
      }
    }
  }
  
  private void estInicialCad(){
    setEstadoCad(false, new JComponent[] {campoRuaCad, btnCadPaciente, campoCidade, campoBairro, campoEstado});
  }
  
  private void estInicialAlt(){
    setEstadoAlt(true, new JComponent[] {campoCpfAlt, btnBuscarCpfAlt, jtbBase});
  }
  
  private void tudoDesabilitadoCad(){
    jtbBase.setEnabled(false);
    setEstadoCad(true, new JComponent[] {});
  }
  
  private void tudoDesabilitadoAlt(){
    jtbBase.setEnabled(false);
    setEstadoAlt(true, new JComponent[] {});
  }
  
  private void tudoHabilitado(){
    jtbBase.setEnabled(true);
    setEstadoCad(false, new JComponent[] {});
  }
  
  private void estadoNaoSeiCep(){
    jtbBase.setEnabled(true);
    setEstadoCad(false, new JComponent[] {campoCepCad, btnBuscarCep, btnNaoSeiCep});
    campoCepCad.setValue(null);
  }
  
  private void limparTudoCad(){
    campoCpfCad.setValue(null);
    campoNomeCad.setText("");
    campoDataNasc.setDate(null);
    campoSaudeCad.setSelectedIndex(0);
    limparEndereco();
  }
  
  private void limparTudoAlt(){
    campoCpfAlt.setValue(null);
    campoNomeAlt.setText("");
    campoDataNascAlt.setDate(null);
    campoSaudeAlt.setSelectedIndex(0);
    campoCepAlt.setValue(null);
    campoRuaAlt.setText("");
    campoBairroAlt.setText("");
    campoNumAlt.setText("");
    campoComplementoAlt.setText("");
    campoCidadeAlt.setText("");
    campoEstadoAlt.setText("");
  }
  
  private void limparEndereco(){
    campoCepCad.setValue(null);
    campoRuaCad.setText("");
    campoNumCad.setText("");
    campoComplemento.setText("");
    campoCidade.setText("");
    campoEstado.setText("");
    campoBairro.setText("");
  }
  
  
  private void btnBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCepActionPerformed
    new Thread(() -> {
      tp.carregando();
      tudoDesabilitadoCad();
      this.enderecoCad = usuarioLogado.buscarCep(campoCepCad.getText());
      if (this.enderecoCad != null) {
        campoRuaCad.setText(enderecoCad.getRua());
        campoCidade.setText(enderecoCad.getCidade());
        campoEstado.setText(enderecoCad.getEstado());
        campoBairro.setText(enderecoCad.getBairro());
        estInicialCad();
        btnCadPaciente.setEnabled(true);
      } else {
        campoCepCad.setValue(null);
        estInicialCad();
      }
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnBuscarCepActionPerformed

  private void btnNaoSeiCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoSeiCepActionPerformed
    sabeCep = false;
    estadoNaoSeiCep();
    limparEndereco();
    campoRuaCad.requestFocus();
  }//GEN-LAST:event_btnNaoSeiCepActionPerformed

  private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    limparTudoCad();
    estInicialCad();
  }//GEN-LAST:event_btnLimparActionPerformed

  private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
    new Thread(() -> {
      tp.carregando();
      tudoDesabilitadoCad();
      
      String cpf = campoCpfCad.getText();
      String nome = campoNomeCad.getText();
//      LocalDate dataNasc = Instant.ofEpochMilli(campoDataNasc.getDate().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
      Date dataNasc = campoDataNasc.getDate();
      boolean isSaude = campoSaudeCad.getSelectedIndex() == 1 ? true : false;
      String cep = null;
      cep = sabeCep ? campoCepCad.getText() : "";
      String rua = campoRuaCad.getText();
      String num = campoNumCad.getText();
      String comp = campoComplemento.getText();
      String bairro = campoBairro.getText();
      String cidade = campoCidade.getText();
      String uf = campoEstado.getText();
      
      int cod = usuarioLogado.cadPaciente(cpf, nome, dataNasc, isSaude, cep, rua, num, bairro, comp, cidade, uf);
      
      if(cod <= 0 && !sabeCep){
        estadoNaoSeiCep();
      }else if(cod <= 0 && sabeCep){
        estInicialCad();
        btnCadPaciente.setEnabled(true);
        campoCepCad.setEnabled(true);
      }else if (cod > 0){
        tp.fila = null;
        tp.s = null;
        estInicialCad();
        limparTudoCad();
      }
      
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnCadPacienteActionPerformed

  private void campoEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEstadoKeyTyped
    if(campoEstado.getText().length() >= 2) evt.consume();
  }//GEN-LAST:event_campoEstadoKeyTyped

  private void campoEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEstadoKeyReleased
    campoEstado.setText(campoEstado.getText().toUpperCase());
  }//GEN-LAST:event_campoEstadoKeyReleased

  private void campoNumCadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumCadKeyTyped
    if (!Pattern.matches("[0-9]", String.valueOf(evt.getKeyChar()))) evt.consume();
    if (campoNumCad.getText().length() >= 5) evt.consume();
  }//GEN-LAST:event_campoNumCadKeyTyped

  private void btnAtuPacienteAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuPacienteAltActionPerformed
    new Thread(() -> {
      tp.carregando();
      tudoDesabilitadoAlt();
      String nome = campoNomeAlt.getText();
//      LocalDate dataNasc = Instant.ofEpochMilli(campoDataNasc.getDate().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
      Date dataNasc = campoDataNascAlt.getDate();
      boolean isSaude = campoSaudeAlt.getSelectedIndex() == 1 ? true : false;
      String cep = campoCepAlt.getText();
      String rua = campoRuaAlt.getText();
      String num = campoNumAlt.getText();
      String comp = campoComplementoAlt.getText();
      String bairro = campoBairroAlt.getText();
      String cidade = campoCidadeAlt.getText();
      String uf = campoEstadoAlt.getText();

      int cod = usuarioLogado.atualizarPaciente(pacienteBuscado, nome, dataNasc, isSaude, cep, rua, num, comp, bairro, cidade, uf);
      System.out.println(cod);
      if (cod > 0) {
        tp.fila = null;
        limparTudoAlt();
        estInicialAlt();
      }else{
        setEstadoAlt(false, new JComponent[] {campoCpfAlt, btnBuscarCpfAlt});
      }
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnAtuPacienteAltActionPerformed

  private void btnExcluirAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAltActionPerformed
    new Thread(() -> {
      tp.carregando();
      tudoDesabilitadoAlt();
      
      int cod = usuarioLogado.removerPaciente(pacienteBuscado.getCpf());
      if (cod > 0) {
        tp.fila = null;
        estInicialAlt();
        limparTudoAlt();
      }
      
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnExcluirAltActionPerformed

  private void campoEstadoAltKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEstadoAltKeyReleased
    campoEstadoAlt.setText(campoEstadoAlt.getText().toUpperCase());
  }//GEN-LAST:event_campoEstadoAltKeyReleased

  private void campoEstadoAltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEstadoAltKeyTyped
    if(campoEstadoAlt.getText().length() >= 2) evt.consume();
  }//GEN-LAST:event_campoEstadoAltKeyTyped

  private void campoNumAltKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumAltKeyTyped
    if (!Pattern.matches("[0-9]", String.valueOf(evt.getKeyChar()))) evt.consume();
    if (campoNumAlt.getText().length() >= 5) evt.consume();
  }//GEN-LAST:event_campoNumAltKeyTyped

  private void btnLimparAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAltActionPerformed
    limparTudoAlt();
    estInicialAlt();
  }//GEN-LAST:event_btnLimparAltActionPerformed

  private void btnBuscarCpfAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCpfAltActionPerformed
    new Thread(() -> {
      tp.carregando();
      tudoDesabilitadoAlt();
      
      pacienteBuscado = usuarioLogado.buscarPaciente(campoCpfAlt.getText());
      if (pacienteBuscado != null) {
        setEstadoAlt(false, new JComponent[]{campoCpfAlt, btnBuscarCpfAlt}); //estado alt busca sucesso
        campoNomeAlt.setText(pacienteBuscado.getNome());
        campoDataNascAlt.setDate(pacienteBuscado.getDataNascAsDate());
        campoSaudeAlt.setSelectedIndex(pacienteBuscado.isSaude() ? 1 : 0);
        campoCepAlt.setText(pacienteBuscado.getEndereco().getCep());
        campoRuaAlt.setText(pacienteBuscado.getEndereco().getRua());
        campoBairroAlt.setText(pacienteBuscado.getEndereco().getBairro());
        campoNumAlt.setText(String.valueOf(pacienteBuscado.getEndereco().getNumero()));
        campoComplementoAlt.setText(pacienteBuscado.getEndereco().getComplemento());
        campoCidadeAlt.setText(pacienteBuscado.getEndereco().getCidade());
        campoEstadoAlt.setText(pacienteBuscado.getEndereco().getEstado());
      } else{
        estInicialAlt();
      }
      tp.carregando();
    }).start();
  }//GEN-LAST:event_btnBuscarCpfAltActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel addPaciente;
  private javax.swing.JPanel altPaciente;
  private javax.swing.JButton btnAtuPacienteAlt;
  private javax.swing.JButton btnBuscarCep;
  private javax.swing.JButton btnBuscarCpfAlt;
  private javax.swing.JButton btnCadPaciente;
  private javax.swing.JButton btnExcluirAlt;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JButton btnLimparAlt;
  private javax.swing.JButton btnNaoSeiCep;
  private javax.swing.JTextField campoBairro;
  private javax.swing.JTextField campoBairroAlt;
  private javax.swing.JFormattedTextField campoCepAlt;
  private javax.swing.JFormattedTextField campoCepCad;
  private javax.swing.JTextField campoCidade;
  private javax.swing.JTextField campoCidadeAlt;
  private javax.swing.JTextField campoComplemento;
  private javax.swing.JTextField campoComplementoAlt;
  private javax.swing.JFormattedTextField campoCpfAlt;
  private javax.swing.JFormattedTextField campoCpfCad;
  private com.toedter.calendar.JDateChooser campoDataNasc;
  private com.toedter.calendar.JDateChooser campoDataNascAlt;
  private javax.swing.JTextField campoEstado;
  private javax.swing.JTextField campoEstadoAlt;
  private javax.swing.JTextField campoNomeAlt;
  private javax.swing.JTextField campoNomeCad;
  private javax.swing.JTextField campoNumAlt;
  private javax.swing.JTextField campoNumCad;
  private javax.swing.JTextField campoRuaAlt;
  private javax.swing.JTextField campoRuaCad;
  private javax.swing.JComboBox<String> campoSaudeAlt;
  private javax.swing.JComboBox<String> campoSaudeCad;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTabbedPane jtbBase;
  // End of variables declaration//GEN-END:variables
}
