/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.AnimaNumeros;
import Modelos.Stats;
import java.text.NumberFormat;

/**
 *
 * @author joaop
 */
public class PagStats extends javax.swing.JPanel implements AnimaNumeros{
  
  private TelaPrincipal tp;
  /**
   * Creates new form PagStats
   */
  public PagStats(TelaPrincipal tp) {
    this.tp = tp;
    initComponents();
    System.out.println(tp.s);
      new Thread(() -> {
        loadStats();
      }).start();
  }
  
  private void loadStats(){
    if(tp.s == null){
      tp.s = Stats.getStats();
      animarNumeros(txtValVac, tp.s.getVacinados(), 0.75);
      animarNumeros(txtValFila, tp.s.getFila(), 0.75);
    } else{
      txtValVac.setText(NumberFormat.getNumberInstance().format(tp.s.getVacinados()) + ""); //comentar Stats caso banco não funcione
      txtValFila.setText(NumberFormat.getNumberInstance().format(tp.s.getFila()) + "");
    }
    
    pnBase.remove(pnLoading);
    pnBase.add(pnInfo);
    revalidate();
    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnInfo = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtValVac = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    txtValFila = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    pnBase = new javax.swing.JPanel();
    pnLoading = new javax.swing.JPanel();
    imgLoading = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Estatísticas do Portal Vacina");

    txtValVac.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValVac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValVac.setText("0");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("pessoas vacinadas!");

    txtValFila.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
    txtValFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtValFila.setText("0");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("pessoas na fila!");

    javax.swing.GroupLayout pnInfoLayout = new javax.swing.GroupLayout(pnInfo);
    pnInfo.setLayout(pnInfoLayout);
    pnInfoLayout.setHorizontalGroup(
      pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
      .addComponent(txtValVac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(pnInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtValFila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnInfoLayout.setVerticalGroup(
      pnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnInfoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(txtValVac)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addGap(50, 50, 50)
        .addComponent(txtValFila)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addContainerGap(146, Short.MAX_VALUE))
    );

    setLayout(new java.awt.BorderLayout());

    pnBase.setLayout(new java.awt.BorderLayout());

    pnLoading.setLayout(new java.awt.BorderLayout());

    imgLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imgLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading.gif"))); // NOI18N
    pnLoading.add(imgLoading, java.awt.BorderLayout.CENTER);

    pnBase.add(pnLoading, java.awt.BorderLayout.CENTER);

    add(pnBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel imgLoading;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel pnBase;
  private javax.swing.JPanel pnInfo;
  private javax.swing.JPanel pnLoading;
  private javax.swing.JLabel txtValFila;
  private javax.swing.JLabel txtValVac;
  // End of variables declaration//GEN-END:variables
}
