/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.Atendente;
import Modelos.Paciente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaop
 */
public class PagVerFila extends javax.swing.JPanel {

  private TelaPrincipal tp;
  private Atendente usuarioLogado;

  /**
   * Creates new form PagVerFila
   */
  public PagVerFila(Atendente usuarioLogado, TelaPrincipal tp) {
    this.tp = tp;
    this.usuarioLogado = usuarioLogado;
    initComponents();
    carregarFila();
  }
  
  private void carregarFila() {
    new Thread(() -> {
      tp.carregando();
      if(tp.fila == null) tp.fila = usuarioLogado.verFila();
      preencherFila();
      tp.carregando();
      btnPagConfVac.setEnabled(true);
    }).start();
  }
  
  private void preencherFila() {
    DefaultTableModel dtm = (DefaultTableModel) tabelaFila.getModel();
    for (Paciente p : tp.fila) {
      dtm.addRow(p.toTableRow());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnBase = new javax.swing.JPanel();
    txtFilaVac = new javax.swing.JLabel();
    jspTabela = new javax.swing.JScrollPane();
    tabelaFila = new javax.swing.JTable();
    btnPagConfVac = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(600, 560));
    setLayout(new java.awt.BorderLayout());

    txtFilaVac.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    txtFilaVac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtFilaVac.setText("Fila de Vacinação");

    tabelaFila.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Nome", "Idade", "Nível", "Saúde"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabelaFila.setShowGrid(true);
    tabelaFila.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tabelaFilaMouseClicked(evt);
      }
    });
    jspTabela.setViewportView(tabelaFila);

    btnPagConfVac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnPagConfVac.setText("Confirmar Vacinação");
    btnPagConfVac.setEnabled(false);
    btnPagConfVac.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPagConfVacActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnBaseLayout = new javax.swing.GroupLayout(pnBase);
    pnBase.setLayout(pnBaseLayout);
    pnBaseLayout.setHorizontalGroup(
      pnBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnBaseLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(btnPagConfVac)
          .addComponent(jspTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
        .addContainerGap())
      .addComponent(txtFilaVac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnBaseLayout.setVerticalGroup(
      pnBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnBaseLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtFilaVac)
        .addGap(18, 18, 18)
        .addComponent(jspTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnPagConfVac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    add(pnBase, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void tabelaFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilaMouseClicked
    
  }//GEN-LAST:event_tabelaFilaMouseClicked

  private void btnPagConfVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagConfVacActionPerformed
    if (tabelaFila.getSelectedRow() == -1) {
      JOptionPane.showMessageDialog(null, "Selecione um Paciente da lista por favor!", "Aviso", JOptionPane.WARNING_MESSAGE);
      return;
    }
    if (tabelaFila.getSelectedRow() != 0) {
      int x = JOptionPane.showConfirmDialog(null, "Este não é o primeiro paciente da fila, deseja confirmar a vacina mesmo assim?", "Aviso", JOptionPane.WARNING_MESSAGE);
      if(x == JOptionPane.YES_OPTION){
        tp.trocarPag(new PagConfVac(tp.fila.get(tabelaFila.getSelectedRow()), this.usuarioLogado, this.tp));
      }else{
        return;
      }
    } else {
      tp.trocarPag(new PagConfVac(tp.fila.get(tabelaFila.getSelectedRow()), this.usuarioLogado, this.tp));
    }
  }//GEN-LAST:event_btnPagConfVacActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnPagConfVac;
  private javax.swing.JScrollPane jspTabela;
  private javax.swing.JPanel pnBase;
  private javax.swing.JTable tabelaFila;
  private javax.swing.JLabel txtFilaVac;
  // End of variables declaration//GEN-END:variables
}
