/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Modelos.Atendente;
import Modelos.Paciente;
import Modelos.Stats;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JComponent;

/**
 *
 * @author W10 VM
 */

public class TelaPrincipal extends javax.swing.JFrame {
  
  public Stats s = null;
  private Atendente usuarioLogado = null;
  private TelaLogin tl = null;
  public boolean filaCarregada = false;
  public ArrayList<Paciente> fila = null;


  /**
   * Creates new form TelaPrincipal
   */
  public TelaPrincipal(Atendente u, TelaLogin tl) {
    this.tl = tl;
    usuarioLogado = u;
    System.out.println(usuarioLogado.getClass());
    antesInit();
    initComponents();
    depoisInit();
    setLocationRelativeTo(null);
  }
  
//  public TelaPrincipal() {
//    usuarioLogado = new Administrador("Admin Teste","111.111.111-11");
//    antesInit();
//    initComponents();
//    depoisInit();
//    setLocationRelativeTo(null);
//    btnSair.setEnabled(false);
//    this.getLayeredPane().setEnabled(false);
//  }
  
  private void antesInit(){
    
  }
  
  private void depoisInit() {
    this.setResizable(false);
    usuarioLogado.setLabelUsuario(txtNomeUsuario);
    removerBtns();
    trocarPag(new PagStats(this));
  }
  
  public void toggleBotoes(){
    btnConfVac.setEnabled(!btnConfVac.isEnabled());
    btnGerPacientes.setEnabled(!btnGerPacientes.isEnabled());
    btnGerUsuarios.setEnabled(!btnGerUsuarios.isEnabled());
    btnGerarRelatorio.setEnabled(!btnGerarRelatorio.isEnabled());
    btnVerFila.setEnabled(!btnVerFila.isEnabled());
    btnSair.setEnabled(!btnSair.isEnabled());
    btnHome.setEnabled(!btnHome.isEnabled());
  }
  
  public void trocarPag(JComponent pag) {
    if (pnPrincipal.getComponentCount() == 0) { //se não houver pag no painel principal
      pnPrincipal.add(pag, BorderLayout.CENTER); //adicionar pag no painel principal
      atualizarTela();
    } else if (pnPrincipal.getComponentCount() > 0) { //se houver pag no painel principal
      if (pnPrincipal.getComponent(0).getClass() != pag.getClass()) { //se a pag atual for diferente da pag a ser inserida
        pnPrincipal.removeAll(); //remove pag atual
        pnPrincipal.add(pag, BorderLayout.CENTER); //adicionar pag no painel principal
        atualizarTela();
      } else { // se pag atual == pag a ser inserida, não faz nada, só retorna
        return;
      }
    }
  }
  
  private void removerBtns() {
    if (usuarioLogado.getClass().equals(Atendente.class)) {
      pnBotoes.remove(btnGerPacientes);
      pnBotoes.remove(btnGerUsuarios);
      pnBotoes.remove(btnGerarRelatorio);
    }
  }
  
  private void atualizarTela(){
    revalidate();
    repaint();
  }
  
  public void carregando() {
    this.toggleBotoes();
    if (this.getCursor().getType() == Cursor.DEFAULT_CURSOR) {
      this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    } else {
      this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnBase = new javax.swing.JPanel();
    pnEsquerda = new javax.swing.JPanel();
    pnLogo = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    pnAcoes = new javax.swing.JPanel();
    pnBotoes = new javax.swing.JPanel();
    btnVerFila = new javax.swing.JButton();
    btnConfVac = new javax.swing.JButton();
    btnGerUsuarios = new javax.swing.JButton();
    btnGerPacientes = new javax.swing.JButton();
    btnGerarRelatorio = new javax.swing.JButton();
    pnDireita = new javax.swing.JPanel();
    pnTopo = new javax.swing.JPanel();
    txtNomeUsuario = new javax.swing.JLabel();
    btnSair = new javax.swing.JLabel();
    btnHome = new javax.swing.JLabel();
    pnPrincipal = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Portal Vacina");
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons8_virus_16px.png")).getImage());

    pnBase.setLayout(new java.awt.BorderLayout());

    pnEsquerda.setBackground(new java.awt.Color(67, 177, 177));
    pnEsquerda.setPreferredSize(new java.awt.Dimension(200, 600));
    pnEsquerda.setLayout(new java.awt.BorderLayout());

    pnLogo.setOpaque(false);
    pnLogo.setPreferredSize(new java.awt.Dimension(200, 200));
    pnLogo.setLayout(new java.awt.BorderLayout());

    logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo vacina 180w.png"))); // NOI18N
    pnLogo.add(logo, java.awt.BorderLayout.CENTER);

    pnEsquerda.add(pnLogo, java.awt.BorderLayout.PAGE_START);

    pnAcoes.setOpaque(false);
    pnAcoes.setLayout(new java.awt.BorderLayout());

    pnBotoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 0, 5));
    pnBotoes.setOpaque(false);
    pnBotoes.setLayout(new java.awt.GridLayout(9, 1, 0, 7));

    btnVerFila.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnVerFila.setForeground(new java.awt.Color(51, 51, 51));
    btnVerFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_queue_32px_1.png"))); // NOI18N
    btnVerFila.setText("Visualizar Fila");
    btnVerFila.setFocusable(false);
    btnVerFila.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnVerFila.setIconTextGap(10);
    btnVerFila.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnVerFila.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVerFilaActionPerformed(evt);
      }
    });
    pnBotoes.add(btnVerFila);

    btnConfVac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnConfVac.setForeground(new java.awt.Color(51, 51, 51));
    btnConfVac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_syringe_32px.png"))); // NOI18N
    btnConfVac.setText("Confirmar Vacina");
    btnConfVac.setFocusable(false);
    btnConfVac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnConfVac.setIconTextGap(10);
    btnConfVac.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnConfVac.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConfVacActionPerformed(evt);
      }
    });
    pnBotoes.add(btnConfVac);

    btnGerUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGerUsuarios.setForeground(new java.awt.Color(51, 51, 51));
    btnGerUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_group_man_man_32px.png"))); // NOI18N
    btnGerUsuarios.setText("Gerenciar Usuários");
    btnGerUsuarios.setFocusable(false);
    btnGerUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnGerUsuarios.setIconTextGap(10);
    btnGerUsuarios.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnGerUsuarios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGerUsuariosActionPerformed(evt);
      }
    });
    pnBotoes.add(btnGerUsuarios);

    btnGerPacientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGerPacientes.setForeground(new java.awt.Color(51, 51, 51));
    btnGerPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_health_checkup_32px.png"))); // NOI18N
    btnGerPacientes.setText("Gerenciar Pacientes");
    btnGerPacientes.setFocusable(false);
    btnGerPacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnGerPacientes.setIconTextGap(10);
    btnGerPacientes.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnGerPacientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGerPacientesActionPerformed(evt);
      }
    });
    pnBotoes.add(btnGerPacientes);

    btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnGerarRelatorio.setForeground(new java.awt.Color(51, 51, 51));
    btnGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_clipboard_list_32px.png"))); // NOI18N
    btnGerarRelatorio.setText("Gerar Relatório");
    btnGerarRelatorio.setFocusable(false);
    btnGerarRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    btnGerarRelatorio.setIconTextGap(10);
    btnGerarRelatorio.setMargin(new java.awt.Insets(2, 5, 2, 5));
    btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGerarRelatorioActionPerformed(evt);
      }
    });
    pnBotoes.add(btnGerarRelatorio);

    pnAcoes.add(pnBotoes, java.awt.BorderLayout.CENTER);

    pnEsquerda.add(pnAcoes, java.awt.BorderLayout.CENTER);

    pnBase.add(pnEsquerda, java.awt.BorderLayout.LINE_START);

    pnDireita.setLayout(new java.awt.BorderLayout());

    pnTopo.setBackground(new java.awt.Color(204, 204, 204));
    pnTopo.setPreferredSize(new java.awt.Dimension(600, 40));

    txtNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    txtNomeUsuario.setText("nome de usuario");

    btnSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_exit_32px.png"))); // NOI18N
    btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnSairMouseClicked(evt);
      }
    });

    btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_home_32px.png"))); // NOI18N
    btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnHomeMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout pnTopoLayout = new javax.swing.GroupLayout(pnTopo);
    pnTopo.setLayout(pnTopoLayout);
    pnTopoLayout.setHorizontalGroup(
      pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnTopoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtNomeUsuario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
        .addComponent(btnHome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnSair)
        .addContainerGap())
    );
    pnTopoLayout.setVerticalGroup(
      pnTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
      .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pnDireita.add(pnTopo, java.awt.BorderLayout.PAGE_START);

    pnPrincipal.setLayout(new java.awt.BorderLayout());
    pnDireita.add(pnPrincipal, java.awt.BorderLayout.CENTER);

    pnBase.add(pnDireita, java.awt.BorderLayout.CENTER);

    getContentPane().add(pnBase, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
    if(tl != null) dispose();
  }//GEN-LAST:event_btnSairMouseClicked

  private void btnGerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerUsuariosActionPerformed
    trocarPag(new PagGerUsuarios(this.usuarioLogado, this));
  }//GEN-LAST:event_btnGerUsuariosActionPerformed

  private void btnVerFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFilaActionPerformed
    trocarPag(new PagVerFila(this.usuarioLogado, this));
  }//GEN-LAST:event_btnVerFilaActionPerformed

  private void btnConfVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfVacActionPerformed
    trocarPag(new PagConfVac(null, this.usuarioLogado, this));    // TODO add your handling code here:
  }//GEN-LAST:event_btnConfVacActionPerformed

  private void btnGerPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerPacientesActionPerformed
    trocarPag(new PagGerPacientes(this.usuarioLogado, this));    // TODO add your handling code here:
  }//GEN-LAST:event_btnGerPacientesActionPerformed

  private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
    trocarPag(new PagGerarRelat(this));   // TODO add your handling code here:
  }//GEN-LAST:event_btnGerarRelatorioActionPerformed

  private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
    trocarPag(new PagStats(this));
  }//GEN-LAST:event_btnHomeMouseClicked

  @Override
  public void dispose() {
    this.usuarioLogado = null;
    tl.setVisible(true);
    tl.limparCampos();
    super.dispose();
  }
  
  
  /**
   * @param args the command line arguments
   */
//  public static void main(String args[]) {
//    /* Set the Nimbus look and feel */
//    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//     */
//    try {
//      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//          javax.swing.UIManager.setLookAndFeel(info.getClassName());
//          break;
//        }
//      }
//    } catch (ClassNotFoundException ex) {
//      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (InstantiationException ex) {
//      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (IllegalAccessException ex) {
//      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//    }
//    //</editor-fold>
//
//    FlatLightLaf.install();
//    /* Create and display the form */
//    java.awt.EventQueue.invokeLater(new Runnable() {
//      public void run() {
//        new TelaPrincipal().setVisible(true);
//      }
//    });
//  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnConfVac;
  private javax.swing.JButton btnGerPacientes;
  private javax.swing.JButton btnGerUsuarios;
  private javax.swing.JButton btnGerarRelatorio;
  private javax.swing.JLabel btnHome;
  private javax.swing.JLabel btnSair;
  private javax.swing.JButton btnVerFila;
  private javax.swing.JLabel logo;
  private javax.swing.JPanel pnAcoes;
  private javax.swing.JPanel pnBase;
  private javax.swing.JPanel pnBotoes;
  private javax.swing.JPanel pnDireita;
  private javax.swing.JPanel pnEsquerda;
  private javax.swing.JPanel pnLogo;
  private javax.swing.JPanel pnPrincipal;
  private javax.swing.JPanel pnTopo;
  private javax.swing.JLabel txtNomeUsuario;
  // End of variables declaration//GEN-END:variables
}
